language: java
sudo : false
dist : trusty
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
before_install:
- rm ~/.m2/settings.xml

matrix: 
  include:
    -env: PROFILE=default
    -env: PROFILE=integration
  
script: 
  - mvn clean install -DskipTests=false -P${PROFILE}
branches:
  only:
  - master
  - "/^2\\.[0-9]{1,}/"
