language: java
sudo : false
dist : trusty
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
before_install:
- rm ~/.m2/settings.xml
script:
  -  mvn clean install -DskipTests=false -DargLine="-Xmx512m -Xms256m" -q -f ./dhis-2/pom.xml
  -  mvn clean install -DskipTests=false -DargLine="-Xmx512m -Xms256m" -q -U -f ./dhis-2/dhis-web/pom.xml
branches:
  only:
  - master
  - "/^2\\.[0-9]{1,}/"
notifications:
  slack:
    rooms:
      secure: W74/QrNS1n3Gxgc/s20Fj/R/6Y9xt//GlIhtilECDGN29koOAbv0Varw6L+Le8ytCy2Np9mlk6zSbjXavVOMX7r4wYPeZwxSXJ/a9EJQiBThQ0N+B53e/KER/nNHtoqiPhZsuSoXQx7oaoeZmT1RLpHpvPZzrWmIr6ViwKHsnI7jnctgITWQSY5WSP9baFvJrIGbVCuM0gPvOKNSwyh2TjML4biH3ZYa/Lv8Qt9y6E36ni0BOGLA6sROc3xCTJCMa/QWU0geRQpTe4Y6FXaNfqZ2GlpRi0CWZ57yXhAxXVE5sDHRLtDG4hvQHmNMgBVi3/zTpkbBLXY8QByYoWtA84dIQpkwfoRPG5QqXZ3AhHIc14oU8B6PcvXD6hAalBYLq+8xf9TKGkOWM4tT83C9UxtrMmjl3ZZz9oHidLfbLYGsggypXWwdV8i9uGau4lomyMVhV63RXtcS5vdrGUQL820YLnAAj5SgVmiyTkYYwEI0s6d+pGjR++S9g7w+JZnwk6EU2xm2bM23ARI7+YKA1j5r0SoAGaXVOgr9oyH+8Qz0g1cvMxG5Akj/E04x/DegjY/maYSccqkt+ug3HrL5spsPA1CljWCD0O7aXS4E07HZZA5sYsmW7goFn8Wu8mtzPiPHi8zjoCfyRdeTpreXS9DcGSZyBtzyuW3zuZcMdhA=
    on_success: change
    on_failure: always
