version: '3'
services:
  db:
    restart: always
    image: mdillon/postgis:10-alpine
    command: postgres -c max_locks_per_transaction=100
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis2
      POSTGRES_PASSOWRD: dhis

  web:
    image: "${IMAGE_NAME}"
    build:
      dockerfile: Dockerfile
      context: ../..
    volumes:
    - ./config/dhis2_home/dhis.conf:/DHIS2_home/dhis.conf
    environment:
    - WAIT_FOR_DB_CONTAINER=db:5432 -t 0
    depends_on:
    - db
    ports:
    - "8080"