version: '3'
services:
  redis:
    image: redis:5.0.5-alpine
    volumes:
    - ./config/redis/redis.conf:/usr/local/etc/redis.conf
    ports:
       - "6379"

  db:
    restart: always
    image: postgis/postgis:10-2.5-alpine
    command: postgres -c max_locks_per_transaction=100
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis2
      POSTGRES_PASSWORD: dhis

  web:
    image: "${IMAGE_NAME}"
    volumes:
    - ./config/dhis2_home/dhis.conf:/DHIS2_home/dhis.conf
    environment:
      - WAIT_FOR_DB_CONTAINER=db:5432 -t 0
      - DHIS2_HOME=/DHIS2_home
    depends_on:
    - db
    - redis
    ports:
    - "8080"
