name: SonarQube analysis
env:
  # This is to make sure Maven don't timeout fetching dependencies. See: https://github.com/actions/virtual-environments/issues/1499
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.httpconnectionManager.ttlSeconds=125
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.DHIS2_BOT_SONARCLOUD_TOKEN }}
on:
  push:
    branches:
      - master
      - '2.3[1-9]'
  pull_request:
    branches:
      - master
      - '2.3[1-9]'
concurrency:
    group: ${{ github.workflow}}-${{ github.ref }}
    cancel-in-progress: true
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - name: Analyse PR
        env:
          BASE_BRANCH: ${{ github.base_ref }}
          BRANCH: ${{ github.ref }}
          PR: ${{ github.event.number }}
        if: github.event_name == 'pull_request'
        run: |
          mvn -f dhis-2/pom.xml clean install --threads 2C --batch-mode --no-transfer-progress -DskipTests
          mvn -f dhis-2/pom.xml sonar:sonar -Dsonar.internal.analysis.dbd=false --batch-mode --no-transfer-progress -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }} -Dsonar.projectKey=dhis2_dhis2-core

      - name: Analyse long-living branch
        if: github.event_name != 'pull_request'
        run: |
          mvn -f dhis-2/pom.xml clean install --threads 2C --batch-mode --no-transfer-progress -DskipTests
          mvn -f dhis-2/pom.xml sonar:sonar -Dsonar.internal.analysis.dbd=false --batch-mode --no-transfer-progress -Dsonar.branch.name=${GITHUB_REF#refs/heads/} -Dsonar.projectKey=dhis2_dhis2-core
